---

- name: MY AS3 PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: false


  vars:
    uri_method: POST


  vars_files:
  -  ../creds/big_creds.yaml

  tasks:

  - name: POST DECLARATION
    uri:
      url: https://3.11.134.160/mgmt/shared/appsvcs/declare/
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json 
      validate_certs: no 
    register: as3_response

  - name: SET FACT FOR VIRTUAL IP
    set_fact: 
      virt_ip: "{{as3_response.json.declaration.Nick_Sample_01.A1.serviceMain.virtualAddresses}}"

  - name: DEBUG OUTPUT AS3 RESPONSE
    debug:
      msg: "{{virt_ip}}"